name: icloud_storage
description: A flutter plugin for uploading and downloading files to and from iCloud.
version: 0.2.3+2
homepage: https://github.com/humanghosts/icloud_storage
publish_to: http://localhost:8080

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: IcloudStoragePlugin
      macos:
        pluginClass: SwiftIcloudStoragePlugin
